language: node_js
node_js:
- '5'
- '4'
script: npm run ci
before_deploy: npm run build
deploy:
  provider: npm
  email: andrew.schrauf@gmail.com
  api_key:
    secure: q8B1iWHnfoVEHwl+4SAcuO/WXRGogZA+mYxxxotQxc+oyTt+bs4lF3l4bRQo7u2aPwb/kY2SEWEkkFKkKzRkAzItXX78MUBBhdy2sfjavaZ9wceO+QzcJeB8MLh5kaz2S8ES+I0RuAVZaordfqq05wuR8ouvJsmZB4UaufgEPAk9CFx4T8gaE9YfkQLbAjtKgrEdvgjzKlkI6vlqmPb2YnNzoqXJP04CiWI+kuM50QiN3mgp/T66WaA854lKPO7h4bZJ+Rgn0PF3lyFmHTb6rlS6S9lnDfvRbSy64u0aqkY8r17qXg0QlX7oFdJf6bruo3sp7WMRLjRJKOtO73i2uvyRMM/1UuLIdG/orMuv+0KcPFgAgDE2t7dMgBfKqOFTMU9wdOLUGm4AKW51zF0BCJjqJpPcb+3478E37ACHNGdktRcAstDhSmfaKZGVjGaLBS+SW2p4wrLxpsdJ+VMGdl+WKqj85kByd4bpJg59OFzZzCe0tXWT3ZyVS8zA9zUh7gqjmnQsVLrR3HOivz8yurcjKr3mQj9s7f/j6FGFiHA+/5scP1JuTprbWZrcz018tSIky7gN+tCJn/69Rrq0RvwtFFuK/vaGQbQ0CdguiSxFbi4ywts90HL5MattwOsd4TBfGFqKj39nM0KbswksCtkMyfnH60DbRW8kZSUJKyc=
  on:
    tags: true
    repo: drewschrauf/webpack-plugin-acid
